// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 地图类型
enum MapType: Int {
  /// 常规地图
  case normal = 0
  /// 卫星地图
  case satellite = 1
  /// 暗色地图
  case dark = 2
}

/// UI控件位置锚点
enum UIControlAnchor: Int {
  case bottomLeft = 0
  case bottomRight = 1
  case topLeft = 2
  case topRight = 3
}

/// 定位模式
///
/// 在地图的各种应用场景中，用户对定位点展示时也希望地图能跟随定位点旋转、移动等多种行为
enum UserLocationType: Int {
  /// 跟踪用户的位置与方向更新，默认是此种类型
  case trackingLocationRotate = 0
  /// 追踪用户的位置更新
  case trackingLocation = 1
  /// 跟踪用户的位置与方向更新，并移动到地图中心（Android only, Android default）
  case trackingLocationRotateCenter = 2
  /// 不追踪用户的位置与方向更新（iOS only）
  case noTracking = 3
  /// 跟踪用户的位置与方向更新，并地图依照用户方向旋转（Android only）
  case trackingRotate = 4
}

/// 限制显示区域模式
enum RestrictRegionMode: Int {
  /// 适配宽度
  case fitWidth = 0
  /// 适配高度
  case fitHeight = 1
}

/// UI控件位置偏移
///
/// Generated class from Pigeon that represents data sent in messages.
struct UIControlOffset {
  /// X轴方向的位置偏移
  var x: Double
  /// Y轴方向的位置偏移
  var y: Double

  static func fromList(_ list: [Any?]) -> UIControlOffset? {
    let x = list[0] as! Double
    let y = list[1] as! Double

    return UIControlOffset(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
}

/// 点标记图标锚点
///
/// Generated class from Pigeon that represents data sent in messages.
struct Anchor {
  /// 点标记图标锚点的X坐标
  var x: Double
  /// 点标记图标锚点的Y坐标
  var y: Double

  static func fromList(_ list: [Any?]) -> Anchor? {
    let x = list[0] as! Double
    let y = list[1] as! Double

    return Anchor(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
}

/// 位置
///
/// Generated class from Pigeon that represents data sent in messages.
struct Position {
  /// 位置的纬度
  var latitude: Double
  /// 位置的经度
  var longitude: Double

  static func fromList(_ list: [Any?]) -> Position? {
    let latitude = list[0] as! Double
    let longitude = list[1] as! Double

    return Position(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
}

/// 定位点
///
/// Generated class from Pigeon that represents data sent in messages.
struct Location {
  /// 定位点的位置
  var position: Position
  /// 定位点的方向
  var heading: Double? = nil
  /// 定位点的精确度
  var accuracy: Double? = nil

  static func fromList(_ list: [Any?]) -> Location? {
    let position = Position.fromList(list[0] as! [Any?])!
    let heading: Double? = nilOrValue(list[1])
    let accuracy: Double? = nilOrValue(list[2])

    return Location(
      position: position,
      heading: heading,
      accuracy: accuracy
    )
  }
  func toList() -> [Any?] {
    return [
      position.toList(),
      heading,
      accuracy,
    ]
  }
}

/// 地图兴趣点
///
/// Generated class from Pigeon that represents data sent in messages.
struct MapPoi {
  /// 兴趣点的名称
  var name: String
  /// 兴趣点的位置
  var position: Position

  static func fromList(_ list: [Any?]) -> MapPoi? {
    let name = list[0] as! String
    let position = Position.fromList(list[1] as! [Any?])!

    return MapPoi(
      name: name,
      position: position
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      position.toList(),
    ]
  }
}

/// 地图视野
///
/// Generated class from Pigeon that represents data sent in messages.
struct CameraPosition {
  /// 地图视野的位置
  var position: Position? = nil
  /// 地图视野的旋转角度
  var heading: Double? = nil
  /// 地图视野的倾斜角度
  var skew: Double? = nil
  /// 地图视野的缩放级别
  var zoom: Double? = nil

  static func fromList(_ list: [Any?]) -> CameraPosition? {
    var position: Position? = nil
    if let positionList: [Any?] = nilOrValue(list[0]) {
      position = Position.fromList(positionList)
    }
    let heading: Double? = nilOrValue(list[1])
    let skew: Double? = nilOrValue(list[2])
    let zoom: Double? = nilOrValue(list[3])

    return CameraPosition(
      position: position,
      heading: heading,
      skew: skew,
      zoom: zoom
    )
  }
  func toList() -> [Any?] {
    return [
      position?.toList(),
      heading,
      skew,
      zoom,
    ]
  }
}

/// 地图区域
///
/// Generated class from Pigeon that represents data sent in messages.
struct Region {
  /// 最北的纬度
  var north: Double
  /// 最东的经度
  var east: Double
  /// 最南的纬度
  var south: Double
  /// 最西的经度
  var west: Double

  static func fromList(_ list: [Any?]) -> Region? {
    let north = list[0] as! Double
    let east = list[1] as! Double
    let south = list[2] as! Double
    let west = list[3] as! Double

    return Region(
      north: north,
      east: east,
      south: south,
      west: west
    )
  }
  func toList() -> [Any?] {
    return [
      north,
      east,
      south,
      west,
    ]
  }
}

/// 视野边缘宽度
///
/// Generated class from Pigeon that represents data sent in messages.
struct EdgePadding {
  /// 上边缘宽度
  var top: Double
  /// 右边缘宽度
  var right: Double
  /// 下边缘宽度
  var bottom: Double
  /// 左边缘宽度
  var left: Double

  static func fromList(_ list: [Any?]) -> EdgePadding? {
    let top = list[0] as! Double
    let right = list[1] as! Double
    let bottom = list[2] as! Double
    let left = list[3] as! Double

    return EdgePadding(
      top: top,
      right: right,
      bottom: bottom,
      left: left
    )
  }
  func toList() -> [Any?] {
    return [
      top,
      right,
      bottom,
      left,
    ]
  }
}

/// 标记点配置属性
///
/// Generated class from Pigeon that represents data sent in messages.
struct MarkerOptions {
  /// 标记点的位置
  var position: Position
  /// 标记点的透明度
  var alpha: Double? = nil
  /// 标记点的旋转角度
  var rotation: Double? = nil
  /// 标记点的Z轴显示顺序
  var zIndex: Int64? = nil
  /// 标记点是否支持3D悬浮（Android Only)
  var flat: Bool? = nil
  /// 标记点是否支持拖动
  var draggable: Bool? = nil
  /// 标记点的图标信息
  var icon: Bitmap? = nil
  /// 标记点的锚点
  var anchor: Anchor? = nil

  static func fromList(_ list: [Any?]) -> MarkerOptions? {
    let position = Position.fromList(list[0] as! [Any?])!
    let alpha: Double? = nilOrValue(list[1])
    let rotation: Double? = nilOrValue(list[2])
    let zIndex: Int64? = list[3] is NSNull ? nil : (list[3] is Int64? ? list[3] as! Int64? : Int64(list[3] as! Int32))
    let flat: Bool? = nilOrValue(list[4])
    let draggable: Bool? = nilOrValue(list[5])
    var icon: Bitmap? = nil
    if let iconList: [Any?] = nilOrValue(list[6]) {
      icon = Bitmap.fromList(iconList)
    }
    var anchor: Anchor? = nil
    if let anchorList: [Any?] = nilOrValue(list[7]) {
      anchor = Anchor.fromList(anchorList)
    }

    return MarkerOptions(
      position: position,
      alpha: alpha,
      rotation: rotation,
      zIndex: zIndex,
      flat: flat,
      draggable: draggable,
      icon: icon,
      anchor: anchor
    )
  }
  func toList() -> [Any?] {
    return [
      position.toList(),
      alpha,
      rotation,
      zIndex,
      flat,
      draggable,
      icon?.toList(),
      anchor?.toList(),
    ]
  }
}

/// 折线配置属性
///
/// Generated class from Pigeon that represents data sent in messages.
struct PolylineOptions {
  /// 折线中拐点位置的列表
  var points: [Position?]? = nil

  static func fromList(_ list: [Any?]) -> PolylineOptions? {
    let points: [Position?]? = nilOrValue(list[0])

    return PolylineOptions(
      points: points
    )
  }
  func toList() -> [Any?] {
    return [
      points,
    ]
  }
}

/// 图片信息
///
/// Generated class from Pigeon that represents data sent in messages.
struct Bitmap {
  /// 图片资源路径
  var asset: String? = nil
  /// 图片数据
  var bytes: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> Bitmap? {
    let asset: String? = nilOrValue(list[0])
    let bytes: FlutterStandardTypedData? = nilOrValue(list[1])

    return Bitmap(
      asset: asset,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      asset,
      bytes,
    ]
  }
}
/// 地图SDK接口
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TencentMapSdkApi {
  /// 初始化地图SDK，显示地图前必须调用
  func initSdk(iosApiKey: String?, agreePrivacy: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TencentMapSdkApiSetup {
  /// The codec used by TencentMapSdkApi.
  /// Sets up an instance of `TencentMapSdkApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TencentMapSdkApi?) {
    /// 初始化地图SDK，显示地图前必须调用
    let initSdkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapSdkApi.initSdk", binaryMessenger: binaryMessenger)
    if let api = api {
      initSdkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let iosApiKeyArg: String? = nilOrValue(args[0])
        let agreePrivacyArg = args[1] as! Bool
        do {
          try api.initSdk(iosApiKey: iosApiKeyArg, agreePrivacy: agreePrivacyArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initSdkChannel.setMessageHandler(nil)
    }
  }
}
private class TencentMapApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return Anchor.fromList(self.readValue() as! [Any?])
      case 129:
        return Bitmap.fromList(self.readValue() as! [Any?])
      case 130:
        return CameraPosition.fromList(self.readValue() as! [Any?])
      case 131:
        return EdgePadding.fromList(self.readValue() as! [Any?])
      case 132:
        return Location.fromList(self.readValue() as! [Any?])
      case 133:
        return MarkerOptions.fromList(self.readValue() as! [Any?])
      case 134:
        return PolylineOptions.fromList(self.readValue() as! [Any?])
      case 135:
        return Position.fromList(self.readValue() as! [Any?])
      case 136:
        return Region.fromList(self.readValue() as! [Any?])
      case 137:
        return UIControlOffset.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class TencentMapApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Anchor {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? Bitmap {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CameraPosition {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? EdgePadding {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Location {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? MarkerOptions {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PolylineOptions {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? Position {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? Region {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? UIControlOffset {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TencentMapApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TencentMapApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TencentMapApiCodecWriter(data: data)
  }
}

class TencentMapApiCodec: FlutterStandardMessageCodec {
  static let shared = TencentMapApiCodec(readerWriter: TencentMapApiCodecReaderWriter())
}

/// 地图操作接口
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TencentMapApi {
  /// 设置地图类型
  func setMapType(type: MapType) throws
  /// 设置个性化地图样式，在官网绑定个性化地图样式，输入样式编号
  func setMapStyle(index: Int64) throws
  /// 设置Logo大小
  func setLogoScale(scale: Double) throws
  /// 设置LOGO的位置
  func setLogoPosition(anchor: UIControlAnchor, offset: UIControlOffset) throws
  /// 设置比例尺的位置
  func setScalePosition(anchor: UIControlAnchor, offset: UIControlOffset) throws
  /// 设置指南针的位置偏移
  func setCompassOffset(offset: UIControlOffset) throws
  /// 设置是否显示指南针
  func setCompassEnabled(enabled: Bool) throws
  /// 设置是否显示比例尺
  func setScaleEnabled(enabled: Bool) throws
  /// 设置比例尺是否淡出
  func setScaleFadeEnabled(enabled: Bool) throws
  /// 设置是否使用旋转手势
  func setRotateGesturesEnabled(enabled: Bool) throws
  /// 设置是否使用滚动手势
  func setScrollGesturesEnabled(enabled: Bool) throws
  /// 设置是否使用缩放手势
  func setZoomGesturesEnabled(enabled: Bool) throws
  /// 设置是否使用倾斜手势
  func setSkewGesturesEnabled(enabled: Bool) throws
  /// 设置是否显示室内图（需要API key支持）
  func setIndoorViewEnabled(enabled: Bool) throws
  /// 设置是否显示室内图楼层控件
  func setIndoorPickerEnabled(enabled: Bool) throws
  /// 设置是否显示路况
  func setTrafficEnabled(enabled: Bool) throws
  /// 设置是否显示建筑物
  func setBuildingsEnabled(enabled: Bool) throws
  /// 设置是否显示3D建筑物
  func setBuildings3dEnabled(enabled: Bool) throws
  /// 设置是否开启定位
  func setMyLocationEnabled(enabled: Bool) throws
  /// 设置定位模式
  func setUserLocationType(type: UserLocationType) throws
  /// 获取当前定位信息
  func getUserLocation() throws -> Location
  /// 移动地图视野
  func moveCamera(position: CameraPosition, duration: Int64) throws
  /// 移动地图视野到某个地图区域
  func moveCameraToRegion(region: Region, padding: EdgePadding, duration: Int64) throws
  /// 移动地图视野到包含一组坐标点的某个地图区域
  func moveCameraToRegionWithPosition(positions: [Position?], padding: EdgePadding, duration: Int64) throws
  /// 限制地图显示区域
  func setRestrictRegion(region: Region, mode: RestrictRegionMode) throws
  /// 添加标记点
  func addMarker(options: MarkerOptions) throws -> String
  /// 添加折线
  func addPolyline(options: PolylineOptions) throws -> String
  /// 开始
  func start() throws
  /// 暂停
  func pause() throws
  /// 恢复
  func resume() throws
  /// 停止
  func stop() throws
  /// 销毁
  func destroy() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TencentMapApiSetup {
  /// The codec used by TencentMapApi.
  static var codec: FlutterStandardMessageCodec { TencentMapApiCodec.shared }
  /// Sets up an instance of `TencentMapApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TencentMapApi?) {
    /// 设置地图类型
    let setMapTypeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setMapType", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMapTypeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = MapType(rawValue: args[0] as! Int)!
        do {
          try api.setMapType(type: typeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMapTypeChannel.setMessageHandler(nil)
    }
    /// 设置个性化地图样式，在官网绑定个性化地图样式，输入样式编号
    let setMapStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setMapStyle", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMapStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let indexArg = args[0] is Int64 ? args[0] as! Int64 : Int64(args[0] as! Int32)
        do {
          try api.setMapStyle(index: indexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMapStyleChannel.setMessageHandler(nil)
    }
    /// 设置Logo大小
    let setLogoScaleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setLogoScale", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogoScaleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let scaleArg = args[0] as! Double
        do {
          try api.setLogoScale(scale: scaleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogoScaleChannel.setMessageHandler(nil)
    }
    /// 设置LOGO的位置
    let setLogoPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setLogoPosition", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLogoPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let anchorArg = UIControlAnchor(rawValue: args[0] as! Int)!
        let offsetArg = args[1] as! UIControlOffset
        do {
          try api.setLogoPosition(anchor: anchorArg, offset: offsetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setLogoPositionChannel.setMessageHandler(nil)
    }
    /// 设置比例尺的位置
    let setScalePositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setScalePosition", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScalePositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let anchorArg = UIControlAnchor(rawValue: args[0] as! Int)!
        let offsetArg = args[1] as! UIControlOffset
        do {
          try api.setScalePosition(anchor: anchorArg, offset: offsetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScalePositionChannel.setMessageHandler(nil)
    }
    /// 设置指南针的位置偏移
    let setCompassOffsetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setCompassOffset", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCompassOffsetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let offsetArg = args[0] as! UIControlOffset
        do {
          try api.setCompassOffset(offset: offsetArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCompassOffsetChannel.setMessageHandler(nil)
    }
    /// 设置是否显示指南针
    let setCompassEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setCompassEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCompassEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setCompassEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCompassEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否显示比例尺
    let setScaleEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setScaleEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScaleEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setScaleEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScaleEnabledChannel.setMessageHandler(nil)
    }
    /// 设置比例尺是否淡出
    let setScaleFadeEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setScaleFadeEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScaleFadeEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setScaleFadeEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScaleFadeEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否使用旋转手势
    let setRotateGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setRotateGesturesEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRotateGesturesEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setRotateGesturesEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRotateGesturesEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否使用滚动手势
    let setScrollGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setScrollGesturesEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScrollGesturesEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setScrollGesturesEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScrollGesturesEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否使用缩放手势
    let setZoomGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setZoomGesturesEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZoomGesturesEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setZoomGesturesEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setZoomGesturesEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否使用倾斜手势
    let setSkewGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setSkewGesturesEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSkewGesturesEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setSkewGesturesEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSkewGesturesEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否显示室内图（需要API key支持）
    let setIndoorViewEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setIndoorViewEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIndoorViewEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setIndoorViewEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIndoorViewEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否显示室内图楼层控件
    let setIndoorPickerEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setIndoorPickerEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIndoorPickerEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setIndoorPickerEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIndoorPickerEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否显示路况
    let setTrafficEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setTrafficEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTrafficEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setTrafficEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTrafficEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否显示建筑物
    let setBuildingsEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setBuildingsEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBuildingsEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setBuildingsEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBuildingsEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否显示3D建筑物
    let setBuildings3dEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setBuildings3dEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBuildings3dEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setBuildings3dEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setBuildings3dEnabledChannel.setMessageHandler(nil)
    }
    /// 设置是否开启定位
    let setMyLocationEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setMyLocationEnabled", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMyLocationEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        do {
          try api.setMyLocationEnabled(enabled: enabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMyLocationEnabledChannel.setMessageHandler(nil)
    }
    /// 设置定位模式
    let setUserLocationTypeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setUserLocationType", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserLocationTypeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let typeArg = UserLocationType(rawValue: args[0] as! Int)!
        do {
          try api.setUserLocationType(type: typeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserLocationTypeChannel.setMessageHandler(nil)
    }
    /// 获取当前定位信息
    let getUserLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.getUserLocation", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getUserLocationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getUserLocation()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getUserLocationChannel.setMessageHandler(nil)
    }
    /// 移动地图视野
    let moveCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.moveCamera", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moveCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionArg = args[0] as! CameraPosition
        let durationArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          try api.moveCamera(position: positionArg, duration: durationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      moveCameraChannel.setMessageHandler(nil)
    }
    /// 移动地图视野到某个地图区域
    let moveCameraToRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.moveCameraToRegion", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moveCameraToRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let regionArg = args[0] as! Region
        let paddingArg = args[1] as! EdgePadding
        let durationArg = args[2] is Int64 ? args[2] as! Int64 : Int64(args[2] as! Int32)
        do {
          try api.moveCameraToRegion(region: regionArg, padding: paddingArg, duration: durationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      moveCameraToRegionChannel.setMessageHandler(nil)
    }
    /// 移动地图视野到包含一组坐标点的某个地图区域
    let moveCameraToRegionWithPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.moveCameraToRegionWithPosition", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moveCameraToRegionWithPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionsArg = args[0] as! [Position?]
        let paddingArg = args[1] as! EdgePadding
        let durationArg = args[2] is Int64 ? args[2] as! Int64 : Int64(args[2] as! Int32)
        do {
          try api.moveCameraToRegionWithPosition(positions: positionsArg, padding: paddingArg, duration: durationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      moveCameraToRegionWithPositionChannel.setMessageHandler(nil)
    }
    /// 限制地图显示区域
    let setRestrictRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.setRestrictRegion", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRestrictRegionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let regionArg = args[0] as! Region
        let modeArg = RestrictRegionMode(rawValue: args[1] as! Int)!
        do {
          try api.setRestrictRegion(region: regionArg, mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRestrictRegionChannel.setMessageHandler(nil)
    }
    /// 添加标记点
    let addMarkerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.addMarker", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addMarkerChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! MarkerOptions
        do {
          let result = try api.addMarker(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addMarkerChannel.setMessageHandler(nil)
    }
    /// 添加折线
    let addPolylineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.addPolyline", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addPolylineChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PolylineOptions
        do {
          let result = try api.addPolyline(options: optionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addPolylineChannel.setMessageHandler(nil)
    }
    /// 开始
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.start", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        do {
          try api.start()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    /// 暂停
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.pause", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { _, reply in
        do {
          try api.pause()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    /// 恢复
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.resume", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeChannel.setMessageHandler { _, reply in
        do {
          try api.resume()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    /// 停止
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.stop", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// 销毁
    let destroyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapApi.destroy", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyChannel.setMessageHandler { _, reply in
        do {
          try api.destroy()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      destroyChannel.setMessageHandler(nil)
    }
  }
}
private class MarkerApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return Anchor.fromList(self.readValue() as! [Any?])
      case 129:
        return Bitmap.fromList(self.readValue() as! [Any?])
      case 130:
        return Position.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class MarkerApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Anchor {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? Bitmap {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? Position {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MarkerApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MarkerApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MarkerApiCodecWriter(data: data)
  }
}

class MarkerApiCodec: FlutterStandardMessageCodec {
  static let shared = MarkerApiCodec(readerWriter: MarkerApiCodecReaderWriter())
}

/// 标记点操作接口
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MarkerApi {
  /// 移除标记点
  func remove(id: String) throws
  /// 更新标记点的位置
  func setPosition(id: String, position: Position) throws
  /// 更新标记点的图标
  func setIcon(id: String, icon: Bitmap) throws
  /// 更新标记点的锚点
  func setAnchor(id: String, anchor: Anchor) throws
  /// 更新标记点的透明度
  func setAlpha(id: String, alpha: Double) throws
  /// 更新标记点的旋转角度
  func setRotation(id: String, rotation: Double) throws
  /// 更新标记点的Z轴显示顺序
  func setZIndex(id: String, zIndex: Int64) throws
  /// 更新标记点的是否可拖拽属性值
  func setDraggable(id: String, draggable: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MarkerApiSetup {
  /// The codec used by MarkerApi.
  static var codec: FlutterStandardMessageCodec { MarkerApiCodec.shared }
  /// Sets up an instance of `MarkerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MarkerApi?) {
    /// 移除标记点
    let removeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.remove", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      removeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.remove(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      removeChannel.setMessageHandler(nil)
    }
    /// 更新标记点的位置
    let setPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setPosition", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let positionArg = args[1] as! Position
        do {
          try api.setPosition(id: idArg, position: positionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPositionChannel.setMessageHandler(nil)
    }
    /// 更新标记点的图标
    let setIconChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setIcon", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setIconChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let iconArg = args[1] as! Bitmap
        do {
          try api.setIcon(id: idArg, icon: iconArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setIconChannel.setMessageHandler(nil)
    }
    /// 更新标记点的锚点
    let setAnchorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setAnchor", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAnchorChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let anchorArg = args[1] as! Anchor
        do {
          try api.setAnchor(id: idArg, anchor: anchorArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAnchorChannel.setMessageHandler(nil)
    }
    /// 更新标记点的透明度
    let setAlphaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setAlpha", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAlphaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let alphaArg = args[1] as! Double
        do {
          try api.setAlpha(id: idArg, alpha: alphaArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAlphaChannel.setMessageHandler(nil)
    }
    /// 更新标记点的旋转角度
    let setRotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setRotation", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let rotationArg = args[1] as! Double
        do {
          try api.setRotation(id: idArg, rotation: rotationArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRotationChannel.setMessageHandler(nil)
    }
    /// 更新标记点的Z轴显示顺序
    let setZIndexChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setZIndex", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setZIndexChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let zIndexArg = args[1] is Int64 ? args[1] as! Int64 : Int64(args[1] as! Int32)
        do {
          try api.setZIndex(id: idArg, zIndex: zIndexArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setZIndexChannel.setMessageHandler(nil)
    }
    /// 更新标记点的是否可拖拽属性值
    let setDraggableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.MarkerApi.setDraggable", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDraggableChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        let draggableArg = args[1] as! Bool
        do {
          try api.setDraggable(id: idArg, draggable: draggableArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDraggableChannel.setMessageHandler(nil)
    }
  }
}
private class TencentMapHandlerCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return CameraPosition.fromList(self.readValue() as! [Any?])
      case 129:
        return Location.fromList(self.readValue() as! [Any?])
      case 130:
        return MapPoi.fromList(self.readValue() as! [Any?])
      case 131:
        return Position.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class TencentMapHandlerCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraPosition {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? Location {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? MapPoi {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? Position {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TencentMapHandlerCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TencentMapHandlerCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TencentMapHandlerCodecWriter(data: data)
  }
}

class TencentMapHandlerCodec: FlutterStandardMessageCodec {
  static let shared = TencentMapHandlerCodec(readerWriter: TencentMapHandlerCodecReaderWriter())
}

/// 地图状态事件回调处理器
///
/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class TencentMapHandler {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return TencentMapHandlerCodec.shared
  }
  /// 当点击地图上任意地点时会触发该回调，方法会传入点击的坐标点，事件可能被上层覆盖物拦截
  func onPress(position positionArg: Position, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onPress", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([positionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当地图上任意地点进行长按点击时会触发该回调，事件可能被上层覆盖物拦截（Android Only）
  func onLongPress(position positionArg: Position, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onLongPress", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([positionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当点击地图上任意的POI时调用，方法会传入点击的POI信息
  func onTapPoi(poi poiArg: MapPoi, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onTapPoi", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([poiArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当地图视野即将改变时会触发该回调（iOS Only）
  func onCameraMoveStart(cameraPosition cameraPositionArg: CameraPosition, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onCameraMoveStart", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([cameraPositionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当地图视野发生变化时触发该回调。视野持续变化时本回调可能会被频繁多次调用, 请不要做耗时或复杂的事情
  func onCameraMove(cameraPosition cameraPositionArg: CameraPosition, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onCameraMove", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([cameraPositionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当地图视野变化完成时触发该回调，需注意当前地图状态有可能并不是稳定状态
  func onCameraMoveEnd(cameraPosition cameraPositionArg: CameraPosition, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onCameraMoveEnd", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([cameraPositionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当点击点标记时触发该回调（Android Only）
  func onTapMarker(markerId markerIdArg: String, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onTapMarker", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([markerIdArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当开始拖动点标记时触发该回调（Android Only）
  func onMarkerDragStart(markerId markerIdArg: String, position positionArg: Position, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onMarkerDragStart", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([markerIdArg, positionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当拖动点标记时触发该回调（Android Only）
  func onMarkerDrag(markerId markerIdArg: String, position positionArg: Position, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onMarkerDrag", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([markerIdArg, positionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当拖动点标记完成时触发该回调（Android Only）
  func onMarkerDragEnd(markerId markerIdArg: String, position positionArg: Position, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onMarkerDragEnd", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([markerIdArg, positionArg] as [Any?]) { _ in
      completion()
    }
  }
  /// 当前位置改变时触发该回调（Android Only）
  func onLocation(location locationArg: Location, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.tencent_map.TencentMapHandler.onLocation", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([locationArg] as [Any?]) { _ in
      completion()
    }
  }
}
